### PR TITLE
Change main entry point to: Copperegg::Alerts

### PR DESCRIPTION
**Pull request by ppp0**
Two modules wrapped in each other, so we don't use the generic `CopperEgg` module name.

Similar to https://github.com/cargomedia/copperegg-revealmetrics/commit/d017af20f7936f294dee882e42ea6a6693528e16

@ppp0 wanna look into this?

### CODE REVIEW

**Comment by ppp0** [comment]
This will be version 0.1.0 (breaking verb changes and general usage)

@njam fancy reviewing ?  all other devs look busy

**Comment by njam** [comment]
- Readme: While you're at it Use `====` and `----` for titles ([example](https://raw.githubusercontent.com/cargomedia/bipbip/master/README.md))
- I assume there are no functional changes in those files with the new module level?

Rest looks good!

**Comment by ppp0** [comment]
* ok
* No, I refactored the methods/verbs to reflect the official docu, but no change in implementation

**Comment by ppp0** [comment]
@njam last check, please

**Comment by njam** [comment]
lgtm!

**Comment by ppp0** [comment]
releasing '0.1.0'

**Pull request merged**
