### PR TITLE
Streamline gemspec file

### PR DESCRIPTION
**Pull request by ppp0**
According to template see https://github.com/cargomedia/bipbip/blob/master/bipbip.gemspec

### CODE REVIEW

**Comment by ppp0** [comment]
@njam please review

**Comment by njam** [comment]
Looks good!

Also bump the minor version, so we can release these small changes?

**Comment by ppp0** [comment]
@njam done

**Comment by njam** [comment]
lgtm

**Comment by ppp0** [comment]
released

**Pull request merged**
