### PR TITLE
Trigger errors on API failures

### PR DESCRIPTION
**Pull request by kris-lab**
If for some reason the initial get in https://github.com/cargomedia/copperegg-alerts/blob/master/lib/copperegg/alerts.rb#L9 fails, we should make sure that either
* other methods don't use `@schedules` unchecked
* raise an error
* raise an error after having retried n times (n>0)  to get an answer

@njam @tomaszdurka @kris-lab what's your favorite?

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam @ppp0 wdyt?

**Comment by ppp0** [comment]
to me, it looks good!

**Comment by njam** [comment]
Introduce `_send(method, path, [body])` and use it in all four cases?

**Comment by kris-lab** [comment]
@njam @ppp0 please re-review

**Comment by njam** [comment]
as discussed let's not use `define_method`

**Comment by kris-lab** [comment]
@njam please review

**Comment by njam** [comment]
lgtm, @ppp0  could you double-check?

**Comment by ppp0** [comment]
* Change the spec title in https://github.com/cargomedia/copperegg-alerts/pull/2/files#diff-b00e26cc02e5f5b6f69d826564a6f280R25 and https://github.com/cargomedia/copperegg-alerts/pull/2/files#diff-b00e26cc02e5f5b6f69d826564a6f280R33 to "fails on.." instead of "returns nil on wrong ..."
* Rationale for adding a ! to https://github.com/cargomedia/copperegg-alerts/pull/2/files#diff-d5be2eb60ef238acd80f2a16fc81d493R50 ? (`merge!` instead of `merge`)

**Comment by kris-lab** [comment]
- ok, makes sense
- `!` will replace old value with new one for variable which I want. The problem was deeper that it actually overrides `@auth` so if you have `post`, `put` and then `get` then the `@auth` would contains data from `put`. It is not used by `get` but it was there!

@njam @ppp0 please re-review

**Comment by ppp0** [comment]
lgtm!

**Pull request merged**
